export default {
  snsContacts: {
    github: {
      address: 'https://github.com/daengdaengLee',
      iconClass: 'icon-github',
      iconText: 'Github',
    },
    facebook: {
      address: 'https://www.facebook.com/gunho.lee.566',
      iconClass: 'icon-facebook',
      iconText: 'Facebook',
    },
    codepen: {
      address: 'https://codepen.io/daengdaengLee/',
      iconClass: 'icon-codepen',
      iconText: 'Codepen',
    },
    mail: {
      address: 'mailto: gunho1020@gmail.com',
      iconClass: 'icon-mail',
      iconText: 'Email',
    },
  },
  avatarImgUrl: 'https://user-images.githubusercontent.com/30795415/33804339-036ace2a-dde6-11e7-9b25-84e6c60be326.jpg',
  projectsInfo: [
    {
      id: 'project-1',
      linkUrl: 'https://daengdaenglee.github.io/calculator_with_vuejs/',
      imgUrl: 'https://user-images.githubusercontent.com/30795415/33804319-b2564816-dde5-11e7-8d4a-60fc12d68898.jpg',
      altMessage: 'web calculator thumbnail image',
      headingText: 'Web Calculator',
      simpleDesc: 'Vue.js를 이용한 간단한 계산기 앱입니다.',
      techStack: 'html, css, javascript, Vue.js, Vuex',
    },
    {
      id: 'project-2',
      linkUrl: 'https://daengdaenglee.github.io/pomodoro_clock_vuejs',
      imgUrl: 'https://user-images.githubusercontent.com/30795415/33947021-b0bd5caa-e066-11e7-809d-659e1eca5fd3.jpg',
      altMessage: 'pomodoro clock thumbnail image',
      headingText: 'Pomodoro Clock',
      simpleDesc: 'Vue.js를 이용한 Pomodoro 시계 앱입니다.',
      techStack: 'html, css, javascript, Vue.js, Vuex',
    },
    {
      id: 'project-3',
      linkUrl: 'https://daengdaenglee.github.io/movie_app_react/',
      imgUrl: 'https://user-images.githubusercontent.com/30795415/34454215-0387aa94-edaa-11e7-9d71-4ff40c916517.jpg',
      altMessage: 'movie app react thumbnail image',
      headingText: 'Movie App React',
      simpleDesc: 'React.js를 이용한 영화 차트 앱입니다.',
      techStack: 'html, css, javascript, React.js',
    },
    {
      id: 'project-4',
      linkUrl: 'https://www.google.com',
      imgUrl: 'https://user-images.githubusercontent.com/30795415/33804328-ddb39bee-dde5-11e7-886e-ee4cee2564d8.jpg',
      altMessage: 'thumbnail image 4',
      headingText: 'Heading Text 4',
      simpleDesc: '',
      techStack: 'Description Text 4',
    },
    {
      id: 'project-5',
      linkUrl: 'https://www.google.com',
      imgUrl: 'https://user-images.githubusercontent.com/30795415/33804330-e4957054-dde5-11e7-99bc-a524087267b6.jpg',
      altMessage: 'thumbnail image 5',
      headingText: 'Heading Text 5',
      simpleDesc: '',
      techStack: 'Description Text 5',
    },
    {
      id: 'project-6',
      linkUrl: 'https://www.google.com',
      imgUrl: 'https://user-images.githubusercontent.com/30795415/33804333-ebb5953a-dde5-11e7-902b-4cdbde57e350.jpg',
      altMessage: 'thumbnail image 6',
      headingText: 'Heading Text 6',
      simpleDesc: '',
      techStack: 'Description Text 6',
    },
    {
      id: 'project-7',
      linkUrl: 'https://www.google.com',
      imgUrl: 'https://user-images.githubusercontent.com/30795415/33804336-f0544e7e-dde5-11e7-9aa5-43260da215cf.jpg',
      altMessage: 'thumbnail image 7',
      headingText: 'Heading Text 7',
      simpleDesc: '',
      techStack: 'Description Text 7',
    },
  ],
  footerInfo: {
    codeRepo: 'https://github.com/daengdaengLee/portfolio',
    userUrl: 'https://daengdaenglee.github.io/portfolio',
  },
  careerInfo: [
    {
      id: 1,
      content: 'I hope to make my career with YOU!<br>Please <strong style="color: gray;">CONTACT ME</strong>!',
    },
  ],
};
